apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-meilisearch-loader
  namespace: data-fabric
  labels:
    k8s-app: kafka-meilisearch-loader
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kafka-meilisearch-loader
  template:
    metadata:
      name: kafka-meilisearch-loader
      namespace: default
      labels:
        k8s-app: kafka-meilisearch-loader
    spec:
      imagePullSecrets:
        - name: ghcr-pat
      containers:
        - name: main
          resources:
            requests:
              cpu: 1000m
              memory: 4000Mi
            limits:
              cpu: 1000m
              memory: 4000Mi
          image: ghcr.io/raft-tech/meilisearch-loader:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER_HOST
              value: df-kafka-brokers.data-fabric:9092
            - name: KAFKA_TOPIC
              value: udl--admin--track
            - name: SCHEMA_REGISTRY_URL
              value: http://df-schema-registry.data-fabric:8081
            - name: MEILISEARCH_URL
              value: "http://meilisearch.default.svc.cluster.local:7700"
            - name: MEILISEARCH_INDEX
              value: "udl-track"
            - name: MEILISEARCH_INSERT_BATCH_SIZE
              value: "1000"
            - name: MEILISEARCH_API_KEY
              value: "aSampleMasterKey"
            - name: MEILISEARCH_INDEX_PRIMARY_KEY
              value: "trkId"